### ISSUE TITLE
API endpoint at apps.nonasoftware.org does not exist

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SBOL-Validator#101]
The documentation refers to a live validation server with an API endpoint at [http://apps.nonasoftware.org/validate](http://apps.nonasoftware.org/validate).

However, the ``apps.nonasoftware.org`` domain does not resolve.

**Comment by cjmyers** [comment]
That one is dead and should be removed from the docs.  You should use:

http://www.async.ece.utah.edu/validate/

**Comment by cjmyers** [comment]
Fixed
