### ISSUE TITLE
Deployment script no longer operational

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-Validator#138]
Dependabot had a whole stack of vulnerabilities pending; I merged in the patches and got the build working again.
Now, however, it appears that the automated deployment no longer works - I suspect this may be due to the secrets pointing at an old location that is no longer valid to deploy to. This is beyond my current knowledge to fix, however, so I hand it back to others to sort.

**Comment by cjmyers** [comment]
Hmm, I'm not sure about that.  The error message is rather cryptic.  @3ach Any ideas?

**Comment by cjmyers** [comment]
I believe this is working again
