### ISSUE TITLE
Add mouse tip help information

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#14]
When you hover over a field, it would be good to include a description of that field.

**Comment by 16zzundel5** [comment]
Added to latest commit and pushed to public instance -- please check.

**Comment by cjmyers** [comment]
Looks good though a couple comments:

1) CD not required for GenBank conversion now, since it can just convert the root CD automatically.
2) Validation options missing tool tips and may be some of the most important ones.

**Comment by 16zzundel5** [comment]
Fixed.
