### ISSUE TITLE
Neglecting rule descriptions the corresponding URIs when multiple validation failures occur

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/SBOL-Validator#15]
The online validator shows only the full message for the first validation exception, but only the rule IDs for the remaining failures. File tested and the screenshot for the results are attached.
<img width="757" alt="screen shot 2016-03-09 at 1 01 54 pm" src="https://cloud.githubusercontent.com/assets/7920249/13648702/41f6c83a-e5f7-11e5-8a5d-5e2a4772daa8.png">
[cello_TetR_exsDA_v2.txt](https://github.com/SynBioDex/SBOL-Validator/files/165983/cello_TetR_exsDA_v2.txt)

**Comment by cjmyers** [comment]
Has this been checked on current JAR?  Could be just the jar out-of-date.

Chris

**Comment by zgzn** [comment]
It could be that the jar was out-of-date. Running this example on with
validation source code produces the complete validation output message.

On Wed, Mar 9, 2016 at 2:12 PM, cjmyers <notifications@github.com> wrote:

> Has this been checked on current JAR? Could be just the jar out-of-date.
>
> Chris
>
> > On Mar 9, 2016, at 1:03 PM, zgzn <notifications@github.com> wrote:
> >
> > The online validator shows only the full message for the first
> validation exception, but only the rule IDs for the remaining failures.
> File tested and the screenshot for the results are attached.
> > <
> https://cloud.githubusercontent.com/assets/7920249/13648702/41f6c83a-e5f7-11e5-8a5d-5e2a4772daa8.png
> >
> > cello_TetR_exsDA_v2.txt <
> https://github.com/SynBioDex/SBOL-Validator/files/165983/cello_TetR_exsDA_v2.txt
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/SynBioDex/SBOL-Validator/issues/15>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SynBioDex/SBOL-Validator/issues/15#issuecomment-194508749>
> .
>



-- 
Zhen Zhang

**Comment by 16zzundel5** [comment]
Updated jar
