### ISSUE TITLE
Allow drag and drop of sbol files on to a drag and drop pad

### ISSUE THREAD

**Issue by hsauro** [SynBioDex/SBOL-Validator#17]
Allow drag and drop of sbol files on to a drag and drop pad. See image below for UI example.

![image](https://cloud.githubusercontent.com/assets/1054990/13746076/c9577ca6-e9ae-11e5-8026-c857dfa20edc.png)

**Comment by 16zzundel5** [comment]
The file upload widget already supports drag and drop in most browsers. I am therefore making this a low-priority fix.

**Comment by 16zzundel5** [comment]
In the interest of keeping the validator small and simple to install, this feature will not be added as it requires import and maintenance of JavaScript libraries and unnecessarily complicates file upload. I have modified the help text to reflect this ability.
