### ISSUE TITLE
Create a web service for libsbolj

### ISSUE THREAD

**Issue by hsauro** [SynBioDex/SBOL-Validator#18]
Create a web service (eg based on Rest, I would avoid WSDL or SOAP that supports a basic libSBOLj API

**Comment by 16zzundel5** [comment]
As far as I understand, we would really only need one endpoint (/validate/) that accepted a file or file URL and returned a validation result, correct?

Zach

**Comment by cjmyers** [comment]
We would need some way to also select options.

Chris

**Comment by 16zzundel5** [comment]
If you were uploading a file, it would be a POST endpoint that could also accept a JSON of specific booleans and strings.

**Comment by 16zzundel5** [comment]
Completed. Awaiting documentation -- will create separate issue.
