### ISSUE TITLE
Conversion flags

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#22]
SBOL 1.1 to 2.0
SBOL 2.0 to 1.1 (-l SBOL1)
SBOL 2.0 to GenBank (-l GenBank)
GenBank to SBOL 2.0 (-g)
Perform file difference checking (-e <compareFile>)
TopLevel URI to Return (-c <conversionTopLevel>)

**Comment by 16zzundel5** [comment]
-l SBOL1 and -l GenBank now changed. Will work on modified input/output selection as discussed today

**Comment by cjmyers** [comment]
Appears to be working.  Thanks.
