### ISSUE TITLE
Fail on first is backwards

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#39]
Right now uncheck means "don't fail on first", so the switch is backwards.  Uncheck should set the flags so it actually does fail on first.

**Comment by 16zzundel5** [comment]
Fixed flipping, but now the detailed stack trace causes the backend to throw a 500 error

**Comment by cjmyers** [comment]
I wonder if this is related to the other bug I’ve encountered with the subtilinsensor file.  Could it be a large report causes this exception?

Chris

**Comment by 16zzundel5** [comment]
Fixed as of latest commit.

**Comment by cjmyers** [comment]
Hi,

Not sure completely working.  The attached file will show first error when fail on first is selected, but it shows all errors when fail on first AND display full stack trace are both selected.

Chris
