### ISSUE TITLE
File names on diff should use original names not hashes

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#41]
The file names reported when difference are found when comparing two should replace hashes with provided file names.

**Comment by 16zzundel5** [comment]
Should probably send filenames to backend so that it can do proper error parsing

**Comment by cjmyers** [comment]
Can now use -mf <str> and -cf <str> to send the validator the names of the files to print when differences are found.

**Comment by 16zzundel5** [comment]
Now uses 'main file' and 'comparison file' to label each file in accordance with the nomenclature used on the frontend. This is a temporary fix until the API can be modified to accept filenames.

**Comment by 16zzundel5** [comment]
Latest commit gives filenames
