### ISSUE TITLE
Problem with displaying some errors.

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#44]
There are problems with displaying some errors.  For the attached file, if you use defaults there are several errors, but you just get this message:

There was an error submitting your request. Try refreshing and submitting again.

If you check non-compliant, it works.  Maybe the size of the error list is causing the problem.

[subtilinsensor.xml.txt](https://github.com/SynBioDex/SBOL-Validator/files/606083/subtilinsensor.xml.txt)

**Comment by 16zzundel5** [comment]
I think that this issue is a symptom of a different and now fixed bug.
