### ISSUE TITLE
Add support for iGEM registry conversion

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#48]
Use James script that converts iGEM XML part information into SBOL.

**Comment by 16zzundel5** [comment]
If I add in support for pulling from the Stack (SynBioHub -- they're one and the same, now, right?) then this issue is moot, right? @cjmyers

**Comment by cjmyers** [comment]
Depends how it is done. There is an igem API that produces an xml file that we could convert but I expect our goal will be to have synbiohub deal with this conversion. So you can close

Chris
