### ISSUE TITLE
Port to the lab webserver

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#51]
Move to the lab web server the development validator/converter.

**Comment by 16zzundel5** [comment]
Done. Moved to [http://www.async.ece.utah.edu/validator](http://www.async.ece.utah.edu/validator) with the API endpoint at [http://www.async.ece.utah.edu/validate](http://www.async.ece.utah.edu/validate). Documentation, GitHub, and group website links have been updated.
