### ISSUE TITLE
No message for 10708 or 10709

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#53]
These are new validation errors appear with no description.  It is appears that your libSBOLj build is not picking up the new rules file.  Please double check that your checkout is completely up-to-date.  Make sure you have the develop branch and do not have any changed files that are not updating.  Please also make sure you are using libSBOLj-2.1.2-SNAPSHOT-withDependencies.jar.

**Comment by 16zzundel5** [comment]
Updated JAR, now showing error messages for 10708 and 10709
