### ISSUE TITLE
Improve output parsing for display

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#59]
Formatting of diff with child differences is losing spaces.

**Comment by 16zzundel5** [comment]
Actually all reported text should trim from the right only, not the left

**Comment by 16zzundel5** [comment]
Also, make sure that newlines between messages generated by libSBOLj are not dropped for ease of reading

**Comment by 16zzundel5** [comment]
Leading whitespace is still being trimmed but blank lines are now preserved

**Comment by 16zzundel5** [comment]
With latest libSBOLj implementing arrows, this is done.
