### ISSUE TITLE
Have validation read in multiple SBOL files

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOL-Validator#7]
Right now, the validator will only read in one sbol file at a time to check for validation. 

It would be useful to have the validator read in multiple sbol files at the same time and display files that were able to pass successfully and files that were not able to pass.

**Comment by cjmyers** [comment]
Perhaps this should be a change to the library to have it read multiple files and give errors for a composite document.

**Comment by eoberortner** [comment]
One simple and initial solution could be to support zip files. Here, the user would have to zip up all relevant SBOL files.

**Comment by cjmyers** [comment]
On the webpage for validator, accept a zip file, unzip, validate all files as specified, give a summary report that lists: file name / success or failure / link to page with detail

**Comment by cjmyers** [comment]
Duplicate
