### ISSUE TITLE
equality return value appears to return true even for unequal files

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#77]
How is this determined?  Is a specific message expected from libSBOLj?

**Comment by 16zzundel5** [comment]
It looks like I mucked up the equality check, the 'equality' attribute is mistakenly just reporting whether or not equality was performed.

**Comment by cjmyers** [comment]
It is tricky because there is no message printed when things are equal only when they are not equal.  You would need to look for non-equal messages.  They include phrase “differ” or “not found in”, if that helps.  Let me know if I should add a message that “No differences are found” or similar.  I went with the “diff” behavior which is no message when no differences.

**Comment by 16zzundel5** [comment]
So ALL of the diff messages include either "differ" or "not found in"?

**Comment by cjmyers** [comment]
Yep

**Comment by 16zzundel5** [comment]
Fixed and pushed. 

Note the new field returned when differences are checked. I've also updated the documentation
