### ISSUE TITLE
Cannot turn off completeness and URI compliance checks from API

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#78]
For options below I would expect URI compliance and completeness not to be checked (i.e., adding the -n and -i flags).  This does not seem to be the case:
     
json: { 'options': {'language' : 'SBOL2',
				  'test_equality': true,
				  'check_uri_compliance': false,
				  'check_completeness': false,
				  'check_best_practices': false,
				  'continue_after_first_error': false,
				  'provide_detailed_stack_trace': false,
				  'insert_type': false,
				  'main_file_name': 'main file',
				  'diff_file_name': 'comparison file',
				 },

**Comment by 16zzundel5** [comment]
Running this command, the API produces the following command:
['/usr/bin/java', '-jar', 'libSBOLj.jar', 'work/43027706-a48a-4117-8bcb-05f5ae1bd07a.sbol', '-o', 'work/b7c1fb63-7b8a-4864-bdb2-b38ac6591b90.gb', '-l', 'GenBank', '-n', '-i']. Have you tested running the JAR on the same file?

**Comment by cjmyers** [comment]
Yes, I also tried it on the web UI, and it also worked fine.  Is the name perhaps wrong in my code (example is SBOL2/igem1.rdf from our test/resources)

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var request = require('request')

const SBOLDocument = require('../lib/SBOLDocument')

var inputFile

readTextFile('file://'+process.argv[2],(err,result) => {
    inputFile = result
})

SBOLDocument.loadRDF(inputFile,(err,sbol) => {
    if (err) {
	console.log(err)
    } else {
	request(
	    { method: 'POST',
	      uri: 'http://www.async.ece.utah.edu/validate/',
	      'content-type': 'application/json',
	      json: { 'options': {'language' : 'SBOL2',
				  'test_equality': true,
				  'check_uri_compliance': false,
				  'check_completeness': false,
				  'check_best_practices': false,
				  'continue_after_first_error': false,
				  'provide_detailed_stack_trace': false,
				  'insert_type': false,
				  'main_file_name': 'main file',
				  'diff_file_name': 'comparison file',
				 },
		      'return_file': true,
		      'main_file': inputFile,
		      'diff_file': sbol.serializeXML({
			  'xmlns:synbiohub': 'http://synbiohub.org#',
			  'xmlns:sybio': 'http://www.sybio.ncl.ac.uk#',
			  'xmlns:rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
			  'xmlns:ncbi': 'http://www.ncbi.nlm.nih.gov#',
			  'xmlns:igem': 'http://synbiohub.org/terms/igem/',
			  'xmlns:gb': 'http://www.ncbi.nlm.nih.gov/',
			  'xmlns:annot' : 'http://myannotation.org/',
			  'xmlns:igem': 'http://parts.igem.org/#',
			  'xmlns:pr' : 'http://partsregistry.org/',
			  'xmlns:grn' : 'urn:bbn.com:tasbe:grn/',
			  'xmlns:myapp' : 'http://www.myapp.org/',
			  'xmlns:sbolhub' : 'http://sbolhub.org/',
			  'xmlns:grn' : 'urn:bbn.com:tasbe:grn/'
		      })
		    }
	    }, function(err, response, body) {
		if(err || response.statusCode >= 300) {
		    console.log('err='+response.statusCode)
		    res.status(response.statusCode).send(err)
		} else {
		    body.errors.forEach((error) => {
			if (!error.toString().startsWith('Namespace')) {
			    console.log(error)
			}
		    })
		};
	    }
	)
    }
})
		 
function readTextFile(file,callback)
{
    var rawFile = new XMLHttpRequest();
    rawFile.open("GET", file, false);
    rawFile.onreadystatechange = function ()
    {
        if(rawFile.readyState === 4)
        {
            if(rawFile.status === 200 || rawFile.status == 0)
            {
                var allText = rawFile.responseText;
                callback(null,allText);
            }
        }
    }
    rawFile.send(null);
}

Chris

**Comment by cjmyers** [comment]
I found the problem.  You return if equality is set and ignore all other commands.  It works now when I removed the return from this file: /var/www/webapps/sbol-validator/src/validator/validator.py

       if self.test_equality and diff_file:
            command += ["-e", diff_file, "-mf", self.main_file_name, "-cf", self
.diff_file_name]
        elif self.test_equality and not diff_file:
            raise ValueError

Have not checked in.  Please double check and check-in if you are okay with it.

Chris

**Comment by 16zzundel5** [comment]
That looks correct. I have checked in and updated the validator on shang.
