### ISSUE TITLE
copy-paste SBOL into ``Paste SBOL'' textarea

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/SBOL-Validator#8]
When pasting SBOL into the ``Paste SBOL'' textarea, the validator should not check if the user wants to upload a file. 
please see screenshot attached.
<img width="1012" alt="screen shot 2016-02-26 at 12 45 01 pm" src="https://cloud.githubusercontent.com/assets/1379942/13365322/361da604-dc89-11e5-8b2b-74bee6e72f23.png">

**Comment by cjmyers** [comment]
Fixed in new validator.
