### ISSUE TITLE
"More info" link is broken

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-Validator#88]
The "More info" link on the live distribution is broken, going to: 
http://www.async.ece.utah.edu/tools/sbol-validatorconverter

I believe that it should be going to the github page instead:
http://synbiodex.github.io/SBOL-Validator/

**Comment by 16zzundel5** [comment]
The link is actually supposed to be pointing to http://www.async.ece.utah.edu/tools/sbol-validatorconverter/, which is an informational page about the validator. Our server hosting that is a bit finicky and requires the trailing slash. I've fixed the issue and deployed the fixed validator.
