### ISSUE TITLE
SBML test breaking GenBank conversion

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-Validator#92]
I am trying to convert a GenBank file to SBOL, and SBOL Validator is erroring out with the following message:

    Exception in thread "main" java.lang.NullPointerException at
    edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.isSBMLFile(SBMLutilities.java:286) at 
    edu.utah.ece.async.ibiosim.conversion.Converter.main(Converter.java:273)`

**Comment by cjmyers** [comment]
There is a problem with the new SBML/SBOL converter code when testing if the file is an SBML file, and it is a GenBank file.  The check should be more robust before we deploy this change, so please revert the converter back to not include the SBML/SBOL converter until this is fixed.
