### ISSUE TITLE
whitespaces in "Main SBOL/GenBank/FASTA File" textarea

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/SBOL-Validator#94]
the textarea contains whitespaces leading to problems when copy-pasting the content of an SBOL-file into the textarea (w/o removing the whitespaces), then the validation the results in an error (screenshot attached).
when removing the leading white-spaces, then there's no error (screenshot attached) 
<img width="1378" alt="validator-error" src="https://user-images.githubusercontent.com/1379942/39085353-fc7bf942-4535-11e8-95e3-3154ab8e1980.png">
<img width="1389" alt="validator-ok" src="https://user-images.githubusercontent.com/1379942/39085354-fc928c20-4535-11e8-8f53-4095f00c819c.png">

Please, can somebody fix the issue that there are no whitespaces in the textarea by default? Thanks!

**Comment by cjmyers** [comment]
Should be fixed.  Please test.

**Comment by eoberortner** [comment]
it's working now! thanks for fixing!
