### ISSUE TITLE
Support import/conversion from GFF

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-Validator#95]
GFF is a commonly used format that is similar to GenBank but also supports hierarchical notation.

Currently, GFF files can be converted into SBOL by down-converting to GenBank (which loses information), and then converting the GenBank to SBOL. 

It would be better to be able to convert directly from GFF to SBOL, so that we don't lose information.

**Comment by cjmyers** [comment]
I've copied this request to the libSBOLj tracker, since conversion is actually supported by libSBOLj.  I will though leave this one open to remind us to add the UI support to the validator/converter once libSBOLj supports GFF.

**Comment by cjmyers** [comment]
Done
