### ISSUE TITLE
Create a new SBOL-Converter frontend

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-Validator#98]
There should be a new SBOL-Converter fronted.  This frontend should default to not have the warnings turned on.  It also should not have the validation options OR comparison options.  The errors reported should only be conversion errors.

**Comment by jakebeal** [comment]
Some validation error should still be thrown, like if the file contains complete uninterpretable nonsense. But we should check only the validation errors that would affect conversion.

**Comment by zachzundel** [comment]
This is ready to test in the conversion-frontend branch. Note that I would run `ln html/form.html .' in the src/conversion-form directory and then access that file from the browser.

**Comment by cjmyers** [comment]
Looks great.  Let's deploy it.

**Comment by cjmyers** [comment]
I tweaked the text on the form to remove mention of validation on the converter form.  I also changed name of the validator/converter form to SBOL Validator.  These are now both deployed.  Note that the validator still has all the functionality and it is primarily for developers.  The converter is limited to just conversion, and it has minimal validation.  

@jakebeal let us know what you think.

**Comment by cjmyers** [comment]
Done
